version: '3.8'
services:
  db-test:
    image: postgres:16-alpine
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    user: '${POSTGRES_USER}'
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 2s
      timeout: 2s
      retries: 2
    volumes:
      - db-test-volume:/var/lib/postgresql/data
    networks:
      - fastify-test
    expose:
      - '${POSTGRES_PORT}'
  api-test:
    user: 'fastify'
    build:
      context: .
      dockerfile: Dockerfile
      target: 'test'
    depends_on:
      db-test:
        condition: service_healthy
    env_file:
      - .env.test
    environment:
      APP_HOST: db-test
    networks:
      - fastify-test
    volumes:
      - ./src:/opt/app/src
    ports:
      - '${APP_PORT}:3000'
    expose:
      - '${APP_PORT}'

volumes:
  db-test-volume:

networks:
  fastify-test:
    driver: bridge
